run maven tests on github actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,6 +9,32 @@ on:
   workflow_dispatch:
 
 jobs:
+
+  tests:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up JDK 11 for x64
+        uses: actions/setup-java@v3
+        with:
+          java-version: '11'
+          distribution: 'temurin'
+          architecture: x64
+
+      - name: Run Tests
+        run: |
+          mvn test jacoco:report
+        working-directory: ${{ github.workspace }}
+
+      - name: Check Test Results
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "Tests passed successfully."
+          else
+            echo "Tests failed."
+            exit 1  # Exit with an error code to stop the workflow
+          fi
+
   build:
     runs-on: ubuntu-latest
 
@@ -36,7 +62,7 @@ jobs:
       - name: Append version to DEBIAN/control
         run: |
           echo "Version: ${{ env.VERSION }}" >> $GITHUB_WORKSPACE/linux-deployment/DEBIAN/control
-          
+
       - name: Set execute permissions for postinst script
         run: chmod 755 $GITHUB_WORKSPACE/linux-deployment/DEBIAN/postinst
 
